export const keywords = {
  shipping: [
    "cash on delivery",
    "cash on delivery tcs",
    "cash on delivery service in pakistan",
    "leopard courier cash on delivery service",
    "best shipping service in pakistan",
  ],
  tracking: [
    "leopard tracking",
    "leopard courier tracking",
    "tcs tracking",
    "tcs courier tracking",
    "blue-ex tracking",
    "blue-ex courier tracking",
    "m&p tracking",
    "m&p courier tracking",
    "trax tracking",
    "trax courier tracking",
    "postex tracking",
    "postex courier tracking",
    "tqs tracking",
    "tqs courier tracking",
    "rider tracking",
    "rider courier tracking",
    "fly courier tracking",
    "do deliver tracking",
    "do deliver courier tracking",
    "call courier tracking",
  ],
  generic: [
    "cash on delivery",
    "cash on delivery tcs",
    "cash on delivery service in pakistan",
    "leopard courier cash on delivery service",
    "best shipping service in pakistan",
    "leopard logistics",
    "tcs logistics",
    "m&p logistics",
    "blue-ex logistics",
    "postex logistics",
    "trax logistics",
    "tqs logistics",
    "rider logistics",
    "fly courier",
    "pos system",
  ],
  aboutus: [
    "cash on delivery",
    "order management system",
    "warehouse management system",
    "inventory control",
    "logistics",
    "shipping portals",
    "leopard logistics",
    "tcs logistics",
    "m&p logistics",
    "blue-ex logistics",
    "postex logistics",
    "trax logistics",
    "tqs logistics",
    "rider logistics",
    "fly courier",
    "pos system",
  ],
};
